steps:
 # Build the container image
 - name: 'gcr.io/cloud-builders/docker'
   args: [ 'build', '-t', 'asia-southeast1-docker.pkg.dev/${_PROJECT_ID}/course-docker/lab-cd:$COMMIT_SHA', '.' ]
 # Push the container image to Artifact Registry
 - name: 'gcr.io/cloud-builders/docker'
   args: ['push', 'asia-southeast1-docker.pkg.dev/${_PROJECT_ID}/course-docker/lab-cd:$COMMIT_SHA']
 # Deploy container image to Cloud Run
 - name: 'gcr.io/cloud-builders/gcloud'
   entrypoint: gcloud
   args:
   - 'run'
   - 'deploy'
   - 'lab-cd'
   - '--image'
   - 'asia-southeast1-docker.pkg.dev/${_PROJECT_ID}/course-docker/lab-cd:$COMMIT_SHA'
   - '--region'
   - 'asia-southeast1'
   - '--allow-unauthenticated'
   - '--platform'
   - 'managed'
   - '--port'
   - '8100'

images:
 - 'asia-southeast1-docker.pkg.dev/${_PROJECT_ID}/course-docker/lab-cd'

substitutions:
  _PROJECT_ID: 'voltaic-wall-405706'
